text = """
Extracted flagChar: C
Extracted flagChar: O
Extracted flagChar: M
Extracted flagChar: P
Extracted flagChar: F
Extracted flagChar: E
Extracted flagChar: S
Extracted flagChar: T
Extracted flagChar: 1
Extracted flagChar: 5
Extracted flagChar: {
Extracted flagChar: d
Extracted flagChar: y
Extracted flagChar: N
Extracted flagChar: 4
Extracted flagChar: M
Extracted flagChar: i
Extracted flagChar: c
Extracted flagChar: _
Extracted flagChar: 1
Extracted flagChar: m
Extracted flagChar: P
Extracted flagChar: 0
Extracted flagChar: r
Extracted flagChar: t
Extracted flagChar: _
Extracted flagChar: 1
Extracted flagChar: S
Extracted flagChar: _
Extracted flagChar: m
Extracted flagChar: 4
Extracted flagChar: g
Extracted flagChar: 1
Extracted flagChar: c
Extracted flagChar: _
Extracted flagChar: 6
Extracted flagChar: f
Extracted flagChar: 2
Extracted flagChar: 6
Extracted flagChar: b
Extracted flagChar: c
Extracted flagChar: d
Extracted flagChar: a
Extracted flagChar: 3
Extracted flagChar: 0
Extracted flagChar: c
Extracted flagChar: d
Extracted flagChar: 8
Extracted flagChar: 5
Extracted flagChar: 5
Extracted flagChar: 1
Extracted flagChar: 3
Extracted flagChar: c
Extracted flagChar: b
Extracted flagChar: a
Extracted flagChar: 3
Extracted flagChar: d
Extracted flagChar: b
Extracted flagChar: 0
Extracted flagChar: a
Extracted flagChar: 5
Extracted flagChar: f
Extracted flagChar: 8
Extracted flagChar: f
Extracted flagChar: 1
Extracted flagChar: 6
Extracted flagChar: f
Extracted flagChar: _
Extracted flagChar: a
Extracted flagChar: b
Extracted flagChar: c
Extracted flagChar: b
Extracted flagChar: a
Extracted flagChar: f
Extracted flagChar: 3
Extracted flagChar: 9
Extracted flagChar: b
Extracted flagChar: 9
Extracted flagChar: 1
Extracted flagChar: 2
Extracted flagChar: e
Extracted flagChar: 3
Extracted flagChar: 4
Extracted flagChar: 3
Extracted flagChar: 6
Extracted flagChar: a
Extracted flagChar: 7
Extracted flagChar: d
Extracted flagChar: 3
Extracted flagChar: a
Extracted flagChar: 3
Extracted flagChar: 5
Extracted flagChar: c
Extracted flagChar: 3
Extracted flagChar: 3
Extracted flagChar: a
Extracted flagChar: 9
Extracted flagChar: f
Extracted flagChar: 2
Extracted flagChar: e
Extracted flagChar: 8
Extracted flagChar: 6
Extracted flagChar: 5
Extracted flagChar: a
Extracted flagChar: 4
Extracted flagChar: f
Extracted flagChar: d
Extracted flagChar: a
Extracted flagChar: _
Extracted flagChar: e
Extracted flagChar: c
Extracted flagChar: 7
Extracted flagChar: e
Extracted flagChar: 3
Extracted flagChar: d
Extracted flagChar: 5
Extracted flagChar: 7
Extracted flagChar: d
Extracted flagChar: 6
Extracted flagChar: 8
Extracted flagChar: 3
Extracted flagChar: 0
Extracted flagChar: 7
Extracted flagChar: 4
Extracted flagChar: 7
Extracted flagChar: 0
Extracted flagChar: 8
Extracted flagChar: 0
Extracted flagChar: 5
Extracted flagChar: a
Extracted flagChar: 9
Extracted flagChar: a
Extracted flagChar: 4
Extracted flagChar: c
Extracted flagChar: 1
Extracted flagChar: e
Extracted flagChar: b
Extracted flagChar: 1
Extracted flagChar: 0
Extracted flagChar: 1
Extracted flagChar: c
Extracted flagChar: c
Extracted flagChar: 2
Extracted flagChar: f
Extracted flagChar: 1
Extracted flagChar: a
Extracted flagChar: c
Extracted flagChar: c
Extracted flagChar: 2
Extracted flagChar: d
Extracted flagChar: e
Extracted flagChar: 0
Extracted flagChar: 9
Extracted flagChar: 4
Extracted flagChar: d
Extracted flagChar: 5
Extracted flagChar: 8
Extracted flagChar: e
Extracted flagChar: 0
Extracted flagChar: 8
Extracted flagChar: b
Extracted flagChar: 8
Extracted flagChar: a
Extracted flagChar: 2
Extracted flagChar: d
Extracted flagChar: 3
Extracted flagChar: b
Extracted flagChar: 9
Extracted flagChar: f
Extracted flagChar: 7
Extracted flagChar: e
Extracted flagChar: e
Extracted flagChar: f
Extracted flagChar: }
"""

flag = ""
for line in text.split('\n'):
    if "Extracted flagChar:" in line:
        flag += line.split(":")[-1].strip()

print("Extracted flag:", flag)
